#!/bin/bash 

MODPATH="./MODULES_F90/"
MAINPATH="./MAIN/"
gfortran -O3 -c ${MODPATH}DISL2D.f90 ${MODPATH}CRACK2D.f90 ${MODPATH}EXTERNAL_FIELD.f90 ${MODPATH}BELEMENT_GEOTWINS.f90 ${MODPATH}COMP_FIELD_GEOTWINS.f90 ${MODPATH}PROPAGATION_GEOTWINS.f90 ${MAINPATH}MAIN_DYKE-CODE_GEOTWINS.f90
rm *.mod
gfortran -O3 -o ${MAINPATH}DYKE-SIMULATION_GEOTWINS *.o -llapack
rm *.o

